# -*- coding: utf-8 -*-
"""Decision Tree (Classification)

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ISF4_DSKr-v5KxPEVswmb8vK1VZiKTN8
"""

import pandas as pd

import numpy as np

import matplotlib.pyplot as plt

import seaborn as sns

df=pd.read_csv("/content/sample_data/Social_Network_Ads.csv")

df

df.info()

df.isnull().sum()

df.describe().T

df.describe()

df.duplicated().sum()

df.duplicated()

X=df.iloc[:,:-1]
y=df['Purchased']

sns.scatterplot(x="Age", y="EstimatedSalary", data=df, hue="Purchased")

from sklearn.preprocessing import StandardScaler

sc=StandardScaler()
sc.fit(X)
sc.transform(X)
X=pd.DataFrame(sc.transform(X),columns=X.columns)

from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

from sklearn.neighbors import KNeighborsClassifier

knn = KNeighborsClassifier(n_neighbors=5)
knn.fit(X_train,y_train)

knn.score(X_test,y_test)*100

knn.score(X_train,y_train)*100

